### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [ArndBrugman/huepi#1]
Hi Arnd,

I work for Philips Hue Developer Support.  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

I had a quick look at your code and in huepi.js (BridgeCreate user method, line 167), the "username" parameter will no longer work after February 2016.  This should be removed and the randomly generated bridge username will be returned in the bridge response.  Apologies for the inconvenience.

Thanks
Steve

**Comment by ArndBrugman** [comment]
Thx!

I will fix this. I already tested this in de debug console and the bridge generates a new ID every time we request one so I ill have to adjust the app as well. I will create a cached bridgeId+key pair in the demo apps (hueMediate and huewi) to show this is working too. And hueNode not to forget :8ball:

**Comment by ArndBrugman** [comment]
I Have updated to this new way of Whitelisting users (devices) and also added cache to make sure we can remember the whitelisting. I am using [BridgeIP]/api/config to gain the BridgeID. I have noticed that this api call is not documented. Is there a specific reason why it is undocumented? Is this api call listed for removal, or is it forgotten to mention in documentation?

**Comment by SteveyO** [comment]
Thanks for updating your API, we have marked it as updated at our end.  
And thanks for pointing out the missing documentation.  It was simply forgotten.  I have added the bridgeid and modelid descriptions to:
http://www.developers.meethue.com/documentation/configuration-api#72_get_configuration   (Login Required).
Steve
