### ISSUE TITLE
Thinks React Native is NodeJS

### ISSUE THREAD

**Issue by abejfehr** [ArndBrugman/huepi#3]
There must be some other way of detecting whether or not the code is running on NodeJS than by checking the existence of `modules`, since `modules` _does_ exist on React Native but modules like `fs` do not.

Currently I have to remove these checks for the library to work.

**Comment by ArndBrugman** [comment]
I have refined the detection of node with:
Object.prototype.toString.call(global.process) === '[object process]'

Please validate if this works for you. Thx!

**Comment by abejfehr** [comment]
That does seem to work, thanks!

Unfortunately, since the library uses other things that are unavailable on React Native, like localStorage, I found that it was just easier to switch to [jsHue](https://github.com/blargoner/jshue). I'll still keep your library in mind for use in web applications :+1:

**Comment by ArndBrugman** [comment]
Thx for checking. Focus for huepi is indeed web and nodejs. Closing issue.
